server:
  port: 9901
eureka:
  instance:
    prefer-ip-address: true

    instance-id: ws://192.168.1.147:9901/
  client:
    service-url:
      defaultZone: http://eureka.dev.yai.im:8900/eureka/
spring:
  application:
    name: im-message-service
  rabbitmq:
    host: 192.168.1.245
    port: 5672
    username: im
    password: 123123
    virtual-host: /
  #Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.1.245  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        timeout: 0 # 连接超时时间（毫秒）
logging:
  level:
    im.kai.server.service.message: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
yai:
  service:
    message:
      app:
        version: 1.0
        updateLog: 初始版本，什么都没有做啊
        updateUrl:
    #websocket聊天服务
    websocket:
      #数据加密密匙
      secretKey: BEFIX98GLCAR60UA
      #数据签名密匙
      signKey: 9OxU5x27Tr5H9OK