spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kai-Peng/kai-imserver.git
          search-paths: /cloud-service-parent/config-server/src/main/resources/config
          username: Kai-Peng
          password: KavyPeng12345