eureka:
  instance:
    prefer-ip-address: true
    ip-address: base-service.dev.yai.im
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
yai:
  service:
    #WebRTC 附件云存储配置信息
    attachments:
      avatar:
        host: http://47.107.127.196:9000
        accessKey: AKIAIOSFODNN7EXAMPLE
        accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        region: default
        bucket: avatar
        putDuration: 3600
        downDuration: 3600
      image:
        host: http://47.107.127.196:9000
        accessKey: AKIAIOSFODNN7EXAMPLE
        accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        region: default
        bucket: image
        putDuration: 7200
        downDuration: 604800
      video:
        host: http://47.107.127.196:9000
        accessKey: AKIAIOSFODNN7EXAMPLE
        accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        region: default
        bucket: video
        putDuration: 3600
        downDuration: 604800
      file:
        host: http://47.107.127.196:9000
        accessKey: AKIAIOSFODNN7EXAMPLE
        accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        region: default
        bucket: file
        putDuration: 3600
        downDuration: 604800
      audio:
        host: http://47.107.127.196:9000
        accessKey: AKIAIOSFODNN7EXAMPLE
        accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        region: default
        bucket: audio
        putDuration: 3600
        downDuration: 604800
    #WebRTC 服务配置信息
    webrtc:
      turn:
        secret: 4080218913 # TURN server secret
        hosts:
        - turn:47.107.127.196:3478
        - turns:47.107.127.196:5349
        - turn:47.107.127.196:5349?transport=udp
        - turns:47.107.127.196:3478?transport=udp
    #websocket聊天服务
    websocket:
      #数据加密密匙
      secretKey: BEFIX98GLCAR60UA
      #数据签名密匙
      signKey: 9OxU5x27Tr5H9OK
