eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.1.245:3306/im_user?useUnicode=true&characterEncoding=utf-8
    username: im
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.1.245  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        timeout: 0 # 连接超时时间（毫秒）